### PR TITLE
updated the first user story and added more tasks

### PR DESCRIPTION
**Pull request by prabhjot023**
I have updated the user stories and added few tasks.

### CODE REVIEW

**Comment by RancyKaur** [comment]
Adding Review - The updates to the story looks fine however first task need to be on first row.

**Review by ronakjpatel — APPROVED** [review]
Yes that is right. Prabhjot.

**Review by RancyKaur — APPROVED** [review]
The changes look fine now. Approving it.

**Review by PreetAngadSingh — APPROVED** [review]
Lgtm

**Comment by ronakjpatel** [comment]
Merging the changes.

**Pull request merged**
