### PR TITLE
login and signup page implementation done and project base structure …

### PR DESCRIPTION
**Pull request by prabhjot023**
login and signup page implementation done and project base structure made.

### CODE REVIEW

**Review by PreetAngadSingh — COMMENTED** [review]
The base structure is good to go, 
Suggestion : application tracking / review application component can be added

**Review by Aakansha08 — COMMENTED** [review]
This looks great. However, can we please add couple more fields against employer sign up page like company address and phone number.

**Comment by prabhjot023** [comment]
> This looks great. However, can we please add couple more fields against employer sign up page like company address and phone number.


> This looks great. However, can we please add couple more fields against employer sign up page like company address and phone number.

I have added the field suggested.

**Review by PreetAngadSingh — APPROVED** [review]
I have checked the functionality, this is working now and the sign up page now has company address and phone number

**Comment by prabhjot023** [comment]
This is related to task #5 & #6

**Pull request merged**
